onyxia:
  ingress:
    enabled: true
    #ingressClassName: nginx
    hosts:
      - host: datalab.lab.192-168-0-17.nip.io
  web:
    env:
      #GLOBAL_ALERT: |
      #  {
      #    severity: "success",
      #    message: {
      #      en: "A **big** announcement! [Check it out](https://example.com)!",
      #      fr: "Une annonce **importante**! [Regardez](https://example.com)!"
      #    }
      #  }
  catalogs:
    [
      {
        "id": "inseefrlab-helm-charts-datascience",
        "name": "Inseefrlab datascience",
        "description": "Services for datascientists. https://github.com/InseeFrLab/helm-charts-datascience",
        "maintainer": "innovation@insee.fr",
        "location": "https://inseefrlab.github.io/helm-charts-datascience",
        "status": "PROD",
        "type": "helm",
      }
    ]
  api:
    regions: [
      {
        id: "my-region",
        name: "My Region",
        description: "Region hosted on my-cluster",
        services: {
          type: "KUBERNETES",
          singleNamespace: true,
          authenticationMode: "serviceAccount",
          expose: {
            domain: "lab.lab.192-168-0-17.nip.io"
          }
        }
      }
    ]
